name: Bundle CI

on:
    push:
        branches: [ main ]
        paths:
            - 'packages/enterprise-security-bundle/**'
            - '.github/workflows/bundle-ci.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'packages/enterprise-security-bundle/**'
            - '.github/workflows/bundle-ci.yml'

jobs:
    build:
        name: "Bundle | PHP ${{ matrix.php }}"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ "8.3" ]
                prefer: [ "lowest", "dist" ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Validate composer.json
                working-directory: packages/enterprise-security-bundle
                run: composer validate --strict

            -   name: Install dependencies (lowest)
                if: matrix.prefer == 'lowest'
                working-directory: packages/enterprise-security-bundle
                run: composer update --prefer-lowest --prefer-stable --no-interaction --no-progress

            -   name: Install dependencies (dist)
                if: matrix.prefer == 'dist'
                working-directory: packages/enterprise-security-bundle
                run: composer update --prefer-dist --no-interaction --no-progress

            -   name: PHPUnit
                working-directory: packages/enterprise-security-bundle
                run: vendor/bin/phpunit

            -   name: PHPStan
                working-directory: packages/enterprise-security-bundle
                run: vendor/bin/phpstan analyse

            -   name: ECS
                working-directory: packages/enterprise-security-bundle
                run: vendor/bin/ecs check
